package nuclei

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/MikeRoss27/scanforge/internal/modules"
	"github.com/MikeRoss27/scanforge/internal/runner"
)

type Module struct {
	binary string
}

func New(binary string) *Module {
	if binary == "" {
		binary = "nuclei"
	}
	return &Module{binary: binary}
}

func (m *Module) Name() string {
	return "nuclei"
}

func (m *Module) Description() string {
	return "Fast and customizable vulnerability scanner"
}

func (m *Module) Requires() []string {
	return []string{"alive_urls"}
}

func (m *Module) Produces() []string {
	return []string{"nuclei_raw"}
}

func (m *Module) Run(ctx context.Context, runCtx *modules.RunContext, executor runner.Executor) (*modules.Result, error) {
	inputArt, err := runCtx.MustArtifact("alive_urls")
	if err != nil {
		return nil, err
	}
	inputFile := runCtx.Run.Path(inputArt.Path)

	opts := runCtx.Nuclei
	if opts.UpdateTemplates {
		updateCmd := runner.Command{
			Name:       m.binary,
			Args:       []string{"-update-templates"},
			Timeout:    10 * time.Minute,
			StdoutFile: runCtx.Run.Path("00_meta", "nuclei-update.stdout.log"),
			StderrFile: runCtx.Run.Path("00_meta", "nuclei-update.stderr.log"),
		}
		if err := runner.AppendCommandLog(runCtx.Run.CommandsLog, updateCmd); err != nil {
			return nil, fmt.Errorf("failed to write commands log: %w", err)
		}
		if _, err := executor.Run(ctx, updateCmd); err != nil {
			return nil, fmt.Errorf("failed to update nuclei templates: %w", err)
		}
	}

	rawOutputFile := runCtx.Run.Path("06_vulns", "nuclei.jsonl")
	stderrFile := runCtx.Run.Path("00_meta", "nuclei.stderr.log")

	severity := opts.Severity
	if severity == "" {
		severity = "low,medium,high,critical"
	}
	rateLimit := opts.RateLimit
	if rateLimit <= 0 {
		rateLimit = 10
	}

	args := []string{
		"-l", inputFile,
		"-silent",
		"-severity", severity,
		"-rate-limit", strconv.Itoa(rateLimit),
		"-jsonl",
	}
	if opts.ExcludeSeverity != "" {
		args = append(args, "-exclude-severity", opts.ExcludeSeverity)
	}
	if opts.Tags != "" {
		args = append(args, "-tags", opts.Tags)
	}
	if opts.ExcludeTags != "" {
		args = append(args, "-exclude-tags", opts.ExcludeTags)
	}
	if opts.TemplatesDir != "" {
		args = append(args, "-t", opts.TemplatesDir)
	}
	args = append(args, runCtx.ProxyArgs("-proxy")...)
	args = append(args, runCtx.HeaderArgs("-H")...)

	cmd := runner.Command{
		Name:       m.binary,
		Args:       args,
		Timeout:    30 * time.Minute,
		StdoutFile: rawOutputFile,
		StderrFile: stderrFile,
	}

	if err := runner.AppendCommandLog(runCtx.Run.CommandsLog, cmd); err != nil {
		return nil, fmt.Errorf("failed to write commands log: %w", err)
	}

	res, err := executor.Run(ctx, cmd)
	if err != nil {
		return nil, fmt.Errorf("failed to run command %q: %w", cmd.Name, err)
	}

	// Findings JSON is now generated by the unified Report Engine.

	if err := runCtx.AddArtifact("nuclei_raw", modules.Artifact{
		Name: "nuclei_raw",
		Type: "jsonl",
		Path: "06_vulns/nuclei.jsonl",
	}); err != nil {
		return nil, fmt.Errorf("failed to publish nuclei results: %w", err)
	}

	status := "completed"
	if res.ExitCode != 0 {
		status = fmt.Sprintf("failed (exit code %d)", res.ExitCode)
	}

	return &modules.Result{
		Name:   m.Name(),
		Status: status,
		OutputFiles: map[string]string{
			"nuclei_raw":    "06_vulns/nuclei.jsonl",
			"nuclei_stderr": "00_meta/nuclei.stderr.log",
		},
	}, nil
}
