// Package nuclei wraps the nuclei vulnerability scanner.
package nuclei

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"

	"github.com/MikeRoss27/scanforge/internal/modules"
	"github.com/MikeRoss27/scanforge/internal/runner"
)

type Module struct {
	binary string
}

func New(binary string) *Module {
	if binary == "" {
		binary = "nuclei"
	}
	return &Module{binary: binary}
}

func (m *Module) Name() string {
	return "nuclei"
}

func (m *Module) Description() string {
	return "Fast and customizable vulnerability scanner"
}

func (m *Module) Requires() []string {
	return []string{"attack_surface_urls"}
}

func (m *Module) Produces() []string {
	return []string{"nuclei_raw"}
}

func (m *Module) Run(ctx context.Context, runCtx *modules.RunContext, executor runner.Executor) (*modules.Result, error) {
	inputArt, err := runCtx.MustArtifact("attack_surface_urls")
	if err != nil {
		return nil, err
	}
	inputFile := runCtx.Run.Path(inputArt.Path)

	opts := runCtx.Nuclei
	if opts.UpdateTemplates {
		updateCmd := runner.Command{
			Name:       m.binary,
			Args:       []string{"-update-templates"},
			Timeout:    10 * time.Minute,
			StdoutFile: runCtx.Run.Path("00_meta", "nuclei-update.stdout.log"),
			StderrFile: runCtx.Run.Path("00_meta", "nuclei-update.stderr.log"),
		}
		if err := runner.AppendCommandLog(runCtx.Run.CommandsLog, updateCmd); err != nil {
			return nil, fmt.Errorf("failed to write commands log: %w", err)
		}
		if _, err := executor.Run(ctx, updateCmd); err != nil {
			return nil, fmt.Errorf("failed to update nuclei templates: %w", err)
		}
	}

	rawOutputFile := runCtx.Run.Path("06_vulns", "nuclei.jsonl")
	stderrFile := runCtx.Run.Path("00_meta", "nuclei.stderr.log")

	severity := opts.Severity
	if severity == "" {
		severity = "low,medium,high,critical"
	}
	rateLimit := opts.RateLimit
	if rateLimit <= 0 {
		rateLimit = 10
	}

	args := []string{
		"-l", inputFile,
		"-silent",
		"-severity", severity,
		"-rate-limit", strconv.Itoa(rateLimit),
		"-jsonl",
		"-matcher-status",
		"-no-mhe",
	}
	if opts.Headless {
		args = append(args, "-headless")
	}
	if opts.ExcludeSeverity != "" {
		args = append(args, "-exclude-severity", opts.ExcludeSeverity)
	}
	if opts.Tags != "" {
		args = append(args, "-tags", opts.Tags)
	}
	if opts.ExcludeTags != "" {
		args = append(args, "-exclude-tags", opts.ExcludeTags)
	}
	if opts.TemplatesDir != "" {
		args = append(args, "-t", opts.TemplatesDir)
	}
	if opts.IncludeCustomTemplates {
		customDir := opts.CustomTemplatesDir
		if customDir == "" {
			customDir = defaultCustomTemplatesDir()
		}
		if customDir != "" {
			args = append(args, "-t", customDir)
		}
	}
	args = append(args, runCtx.ProxyArgs("-proxy")...)
	args = append(args, runCtx.HeaderArgs("-H")...)

	cmd := runner.Command{
		Name:       m.binary,
		Args:       args,
		Timeout:    30 * time.Minute,
		StdoutFile: rawOutputFile,
		StderrFile: stderrFile,
	}

	if err := runner.AppendCommandLog(runCtx.Run.CommandsLog, cmd); err != nil {
		return nil, fmt.Errorf("failed to write commands log: %w", err)
	}

	// Nuclei can run for tens of minutes; tail the JSONL it streams results
	// to so matches surface live instead of only once the whole scan ends.
	// tailDone is awaited (not fire-and-forget) so the final flush - which
	// picks up whatever nuclei wrote right before exiting - has actually run
	// before this module returns.
	stop := make(chan struct{})
	tailDone := make(chan struct{})
	go func() {
		defer close(tailDone)
		modules.TailLines(rawOutputFile, stop, 500*time.Millisecond, func(line string) {
			emitNucleiFinding(runCtx, line)
		})
	}()

	res, err := executor.Run(ctx, cmd)
	close(stop)
	<-tailDone
	if err != nil {
		return nil, fmt.Errorf("failed to run command %q: %w", cmd.Name, err)
	}

	// Findings JSON is now generated by the unified Report Engine.

	if err := runCtx.AddArtifact("nuclei_raw", modules.Artifact{
		Name: "nuclei_raw",
		Type: "jsonl",
		Path: "06_vulns/nuclei.jsonl",
	}); err != nil {
		return nil, fmt.Errorf("failed to publish nuclei results: %w", err)
	}

	status := "completed"
	if res.ExitCode != 0 {
		status = fmt.Sprintf("failed (exit code %d)", res.ExitCode)
	}

	return &modules.Result{
		Name:   m.Name(),
		Status: status,
		OutputFiles: map[string]string{
			"nuclei_raw":    "06_vulns/nuclei.jsonl",
			"nuclei_stderr": "00_meta/nuclei.stderr.log",
		},
	}, nil
}

// emitNucleiFinding parses one line of nuclei's JSONL stream and, if it is a
// genuine match, reports it live via runCtx.EmitFinding. Malformed lines
// (e.g. a line read mid-write) and non-matches (matcher-status=false, used
// with OR-matcher templates) are silently skipped; the final report parser
// re-reads the completed file and is the source of truth.
func emitNucleiFinding(runCtx *modules.RunContext, line string) {
	var record struct {
		TemplateID    string `json:"template-id"`
		MatchedAt     string `json:"matched-at"`
		Host          string `json:"host"`
		MatcherStatus *bool  `json:"matcher-status"`
		Info          struct {
			Name     string `json:"name"`
			Severity string `json:"severity"`
		} `json:"info"`
	}
	if err := json.Unmarshal([]byte(line), &record); err != nil {
		return
	}
	if record.MatcherStatus != nil && !*record.MatcherStatus {
		return
	}

	target := record.Host
	if target == "" {
		target = record.MatchedAt
	}
	if target == "" {
		return
	}

	title := record.Info.Name
	if title == "" {
		title = record.TemplateID
	}

	runCtx.EmitFinding(modules.Finding{
		Module:   "nuclei",
		Severity: record.Info.Severity,
		Title:    title,
		Target:   target,
		Detail:   record.MatchedAt,
	})
}

// defaultCustomTemplatesDir locates the bundled custom template directory via
// SCANFORGE_TEMPLATES_DIR, the working directory or the executable directory,
// or "" when absent.
func defaultCustomTemplatesDir() string {
	if fromEnv := os.Getenv("SCANFORGE_TEMPLATES_DIR"); fromEnv != "" {
		if info, err := os.Stat(fromEnv); err == nil && info.IsDir() {
			return fromEnv
		}
	}
	for _, rel := range []string{"templates", filepath.Join("..", "templates")} {
		if abs, err := filepath.Abs(rel); err == nil {
			if info, err := os.Stat(abs); err == nil && info.IsDir() {
				return abs
			}
		}
	}
	if exe, err := os.Executable(); err == nil {
		dir := filepath.Dir(exe)
		for _, rel := range []string{"templates", filepath.Join("..", "templates")} {
			p := filepath.Join(dir, rel)
			if info, err := os.Stat(p); err == nil && info.IsDir() {
				return p
			}
		}
	}
	return ""
}
